blogs/urls.py
from django.urls import path

from . import views
app_name = 'blogs'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create/', views.create, name='create'),
    path('save/', views.save, name='save')
        ]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('blogs/', include('blogs.urls')),
    path('admin/', admin.site.urls)
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
#urlpatterns = [
#    path('', views.index, name='index'),
#    path('<int:question_id>/', views.detail, name='detail'),
#    path('<int:question_id>/results/', views.results, name='results'),
#    path('<int:question_id>/vote/', views.vote, name='vote')
#        ]

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote')
        ]

blogs/models.py
from django.db import models

class Title(models.Model):
    title_text = models.CharField(max_length=75)
    pub_date = models.DateTimeField(auto_now_add = True) 

    def __str__(self):
        return self.title_text


class Body(models.Model):
   title = models.ForeignKey(Title, on_delete=models.CASCADE)
   body_text = models.CharField(max_length=200)

   def __str__(self):
       return self.body_text

polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

blogs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.views import generic
from django.urls import reverse

from .models import Title, Body

class IndexView(generic.ListView):
    template_name = 'blogs/index.html'
    context_object_name = 'titles'

    def get_queryset(self): 
        return Title.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Title
    template_name = 'blogs/detail.html'

def create(request):
    return render(request, 'blogs/create.html')




def save(request):
    title_text = request.POST['title_text']
    body_text = request.POST['body_text']

    title = Title(title_text=title_text)
    title.save()

    title = Title.objects.latest('id')

    body = Body(body_text=body_text, title=title)
    body.save()

    return HttpResponseRedirect(reverse('blogs:index'))

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Question, Choice

#def index(request):
#    latest_question_list = Question.objects.order_by('-pub_date')[:5]
#    context = {'latest_question_list' : latest_question_list}
#    return render(request, 'polls/index.html', context)



#def detail(request, question_id):
    #return HttpResponse('your looking at question %s.' % question_id)
#    question = get_object_or_404(Question, pk=question_id)
#    return render(request, 'polls/detail.html', {'question' : question})



#def results(request, question_id):
    #response = 'yur looking to results of question %s'
    #return HttpResponse(response % question_id)
#    question = get_object_or_404(Question, pk=question_id)
#    return render(request, 'polls/results.html', {'question':question})




#generic views
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]



class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'



class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    #return HttpResponse('Your voting on question %s' % question_id)
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'you didnt select a choice'})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,) ))

blogs/templates/blogs/base.html
<ul>
	<li><a href='{% url "blogs:index" %}'>home</a></li>
	<li><a href='{% url "blogs:create" %}'>write blog</a></li>
</ul>

{% block content %}{% endblock content %}

blogs/templates/blogs/create.html
{% extends 'blogs/base.html' %}

{% block content %}
<form action='{% url "blogs:save" %}' method='post'>
{% csrf_token %}
	<label> Title : </label> <br>
	<input type='text' name='title_text'> <br>

	<label> Body: </label> <br>
	<textarea rows='4' cols='20' name='body_text'>
	</textarea> <br>

	<input type='submit' value='Post'>
</form>

{% endblock content%}

blogs/templates/blogs/detail.html
{% extends 'blogs/base.html' %}
{% block content %}

{% if error_message %}
	{{ error_message }}
{% endif %}
<code> {{ title.title_text }} <br>
	{{ title.pub_date }}
</code>
{% for body in title.body_set.all %}
	<p>{{ body.body_text }}</p>
{% endfor %}
{% endblock content %}

blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}


{% block content %}

{% load static %}
<link rel='stylesheet' type='text/css' href='{% static "blogs/style.css" %}'>

{% for title in titles %}
<p><a href="{% url 'blogs:detail' title.id %}">{{title.title_text}} </a> </p>
{% endfor %}
{% endblock content %}

polls/templates/polls/detail.html
{% if error_message %}
<p>
{{error_message}}
</p>
{% endif %}
<form action='{% url "polls:vote" question.id %}' method='post'>
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type='radio' name='choice' id='choice{{ forloop.counter }}'
	       value='{{choice.id}}'>
	<label for='choice{{forloop.counter}}'>{{ choice.choice_text}} </label> <br>
{% endfor %}
<input type='submit' value='Vote'>
</form>

polls/templates/polls/index.html
{% load static %}
<link rel='stylesheet' type='text/css' href="{% static 'polls/style.css' %}">


{% if latest_question_list %}
	<ul>
		{% for question in latest_question_list %}
		<li> <a href='{% url "polls:detail" question.id %}'>
				{{question.question_text}}
		</a></li>	
		{% endfor %}
	</ul>
{% else %}
	<p>No polls are available</p>
{% endif %}

polls/templates/polls/results.html
<b> {{ question.question_text}} </b>

<ul>
	{% for choice in question.choice_set.all %}
		<li>{{ choice.choice_text}} -- {{choice.votes}}
			vote{{choice.votes|pluralize}}
		</li>
	{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>